language: python
python:
  - "2.7"
services:
  - docker
script:
  - docker login -u${DOCKER_USER} -p${DOCKER_USER_PASSWORD}
  - pip install jinja2
  - chmod +x sync.py
  - ./sync.py
branches:
  only:
    - sync
notifications:
  email:
    recipients:
      - me@xiexianbin.cn
    on_success: always # default: change
    on_failure: always # default: always
